### ISSUE TITLE
建议仿照Spring Boot多模块的参考实现，将litemall-core、litemall-db等模块的application删除

### ISSUE THREAD

**Issue by wlnirvana** [linlinjava/litemall#313]
在Spring Boot官方的多模块[参考例子][1]中，作者专门强调：

> The Library project has no class with a main method (because it is not an application).

相应地，在[官方代码][2]中，有`main`方法的类也被删去了。

建议对于`core`、`db`等模块，也将相关的类删去。

[1]:https://spring.io/guides/gs/multi-module/#setting-up-the-library-project
[2]:https://github.com/spring-guides/gs-multi-module/tree/master/complete/library/src/main/java/com/example/multimodule/service

**Comment by SerenoShen** [comment]
作者一开始的规划便是微服务spring cloud方面发展，保留着每个模块独立运行的能力，没必要删除




            
            
                
                    
                            
                                
                            
                            
                                leishen
                            
                    
                        
                            
                                    邮箱：sereno@aliyun.com
                            
                        
                
            
        Signature is customized by Netease Mail Master


在2019年12月27日 19:19，wlnirvana 写道： 在Spring Boot官方的多模块参考例子中，作者专门强调：

The Library project has no class with a main method (because it is not an application).

相应地，在官方代码中，有main方法的类也被删去了。

建议对于core、db等模块，也将相关的类删去。

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/linlinjava/litemall/issues/313?email_source=notifications\u0026email_token=ADD2PKHTSSHSSDJMEFCBMMLQ2XQE7A5CNFSM4J72SMDKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IC3DU3A",
"url": "https://github.com/linlinjava/litemall/issues/313?email_source=notifications\u0026email_token=ADD2PKHTSSHSSDJMEFCBMMLQ2XQE7A5CNFSM4J72SMDKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IC3DU3A",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by wlnirvana** [comment]
@SerenoShen 

core和db自己应该不是微服务，不能独立运行，参考[作者的回答][1]。现在保留'Application.java`似乎主要是为了测试，但可以考虑把`Application.java`移到测试目录下，使得结构更清晰一些。

[1]:https://github.com/linlinjava/litemall/issues/189#issuecomment-497575902

**Comment by linlinjava** [comment]
其实两位说的都有道理，我一开始只是想着测试用，现在放在test目录下面。
4c46da9ba1a4bb741498f660c23eeb70ff110fea

**Comment by wangduheng** [comment]
把litemall-core、litemall-db模块中订单application移走后，项目该怎么编译呢？直接执行mvn install 报litemall-db找不到主类呢？
